filebeat.inputs:
  - type: filestream
    id: api-server-json
    enabled: true
    paths:
      - /var/log/app/json/*.json
    parsers:
      - ndjson:
          keys_under_root: true
          overwrite_keys: true
          add_error_key: true
    fields:
      service: api-server
    fields_under_root: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
